#!/bin/sh
(set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix

basedir=`dirname "$0"`

case=`uname` in
  *MINGW*)
    *CYGWIN*)
    if [ -f "$NPM_PREFIX_NPM_CLI_JS" ]; then
      fi
    ;;
esac


